---
title: notepad
baseurl: ""
desc: A minimal blog for off-topic blog entries.
about: It is notepad.
image: https://pinto-light.glitch.me/?width=500&height=500&url=https://www.funnyjokesblog.com/images/funny-cats/funny-cat-11.jpg&extension=jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
